baseURL = "https://greenstatic.dev"
languageCode = "en-us"
title = "greenstatic.dev"
theme = "greenstatic-blog"


[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.goldmark]
      [markup.goldmark.renderer]
      unsafe = true
